// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingConsole.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728132847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingConsole.Models.Account.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasDiscriminator<int>("AccountType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KycNextOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KycOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("KycStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TaxIssuedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasDiscriminator<int>("CustomerType").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.CustomerAction", b =>
                {
                    b.Property<Guid>("CustomerActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerActionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("CustomerId", "Timestamp");

                    b.ToTable("CustomerActions");
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.CustomerRole", b =>
                {
                    b.Property<Guid>("CustomerRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IndividualCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InstitutionalCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NomineeForCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerRoleId");

                    b.HasIndex("IndividualCustomerId");

                    b.HasIndex("InstitutionalCustomerId");

                    b.HasIndex("NomineeForCustomerId")
                        .IsUnique();

                    b.ToTable("CustomerRoles");
                });

            modelBuilder.Entity("BankingConsole.Models.LedgerEntry", b =>
                {
                    b.Property<Guid>("LedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("Flow")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LedgerEntryId");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("BankingConsole.Models.Product.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AllowPremature")
                        .HasColumnType("bit");

                    b.Property<int>("AllowedCustomerType")
                        .HasColumnType("int");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("InterestFlow")
                        .HasColumnType("int");

                    b.Property<Guid>("InterestOfficeAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("InterestPostPolicies")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("InterestPostingFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsMaturityProduct")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PostInterestToLinkedAccount")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<Guid>("TaxOfficeAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("TenureInDays")
                        .HasColumnType("int");

                    b.Property<int?>("TransferCount")
                        .HasColumnType("int");

                    b.Property<int?>("TransferFlow")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransferPenaltyRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("ProductId");

                    b.HasIndex("InterestOfficeAccountId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("TaxOfficeAccountId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BankingConsole.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankingConsole.Models.TransactionAction", b =>
                {
                    b.Property<Guid>("TransactionActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewState")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PreviousState")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionActionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionActions");
                });

            modelBuilder.Entity("BankingConsole.Models.Account.CustomerAccount", b =>
                {
                    b.HasBaseType("BankingConsole.Models.Account.Account");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisbursementAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FundingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InterestAccured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InterestCalculatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InterestPostedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MaturitySettlementAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OutstandingPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<Guid?>("RepaymentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RepaymentInstallments")
                        .HasColumnType("int");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DisbursementAccountId");

                    b.HasIndex("FundingAccountId");

                    b.HasIndex("MaturitySettlementAccountId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RepaymentAccountId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("BankingConsole.Models.Account.OfficeAccount", b =>
                {
                    b.HasBaseType("BankingConsole.Models.Account.Account");

                    b.Property<int>("OfficeAccountType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.IndividualCustomer", b =>
                {
                    b.HasBaseType("BankingConsole.Models.Customer.Customer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Nationality")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NomineeAddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Occupation")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.InstitutionalCustomer", b =>
                {
                    b.HasBaseType("BankingConsole.Models.Customer.Customer");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasFilter("[RegistrationNumber] IS NOT NULL");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.Customer", b =>
                {
                    b.OwnsMany("BankingConsole.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AddressId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("CustomerId", "AddressId");

                            b1.ToTable("CustomerAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("BankingConsole.Models.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContactId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit");

                            b1.Property<string>("Mobile")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("CustomerId", "ContactId");

                            b1.HasIndex("Email");

                            b1.ToTable("CustomerContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("BankingConsole.Models.Identity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("IdentityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("ExpiryDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("IssuedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("IssuingAuthority")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("IssuingCountry")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("CustomerId", "IdentityId");

                            b1.HasIndex("DocumentNumber", "IssuingCountry")
                                .IsUnique();

                            b1.ToTable("CustomerIdentities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Contact");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.CustomerAction", b =>
                {
                    b.HasOne("BankingConsole.Models.Customer.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.CustomerRole", b =>
                {
                    b.HasOne("BankingConsole.Models.Customer.IndividualCustomer", "IndividualCustomer")
                        .WithMany()
                        .HasForeignKey("IndividualCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingConsole.Models.Customer.InstitutionalCustomer", null)
                        .WithMany("Roles")
                        .HasForeignKey("InstitutionalCustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BankingConsole.Models.Customer.IndividualCustomer", null)
                        .WithOne("Nominee")
                        .HasForeignKey("BankingConsole.Models.Customer.CustomerRole", "NomineeForCustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("IndividualCustomer");
                });

            modelBuilder.Entity("BankingConsole.Models.LedgerEntry", b =>
                {
                    b.HasOne("BankingConsole.Models.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingConsole.Models.Transaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankingConsole.Models.Product.Product", b =>
                {
                    b.HasOne("BankingConsole.Models.Account.OfficeAccount", null)
                        .WithMany()
                        .HasForeignKey("InterestOfficeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingConsole.Models.Account.OfficeAccount", null)
                        .WithMany()
                        .HasForeignKey("TaxOfficeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingConsole.Models.TransactionAction", b =>
                {
                    b.HasOne("BankingConsole.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingConsole.Models.Account.CustomerAccount", b =>
                {
                    b.HasOne("BankingConsole.Models.Customer.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingConsole.Models.Account.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("DisbursementAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankingConsole.Models.Account.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("FundingAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankingConsole.Models.Account.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("MaturitySettlementAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankingConsole.Models.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingConsole.Models.Account.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("RepaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BankingConsole.Models.Transaction", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.IndividualCustomer", b =>
                {
                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("BankingConsole.Models.Customer.InstitutionalCustomer", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
